<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Book a call_insent-popup-card-close-icon</name>
   <tag></tag>
   <elementGuidId>9803ec67-83a9-4413-9c17-1eb5bf11a7f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='insent-popup-card-close-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#insent-popup-card-close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#insent-popup-card-close-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5092b95a-10bb-4008-aa3d-3c21e5335de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insent-popup-card-close-icon</value>
      <webElementGuid>bc72018b-30ac-4479-a59c-b04967f387b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/close.ec75d473.svg</value>
      <webElementGuid>fafd78a1-d148-4691-aeb8-29c5e7f027cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cEvuZC gxfXwW</value>
      <webElementGuid>4e8e76bb-501c-4652-be5b-c2af1bcf16a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insent-popup-card-close-icon&quot;)</value>
      <webElementGuid>2ece0366-43c6-4ade-9f14-d9a2d3b8bff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Software Quality Management Platform  _0ea48f/iframe_concat(id(, , insent-iframe, , ))_in_d2847a</value>
      <webElementGuid>9098576b-4bbf-4148-b84f-258db3b8e5bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='insent-popup-card-close-icon']</value>
      <webElementGuid>f2f17bc2-7b94-4ac1-8aed-177dcf544ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insent-popup-card-close']/img</value>
      <webElementGuid>92d9b8bb-628c-491a-b096-9271e586df83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>36cc954c-4147-4731-987b-7f8ac11a960f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'insent-popup-card-close-icon' and @src = '/static/media/close.ec75d473.svg']</value>
      <webElementGuid>9098e770-b17b-45bc-baf2-53dc953b8bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
